# Site settings
title: "Taeuk Kim Resume"
description: "My Resume by Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Taeuk Kim"
resume_title:                   "Cloud/Storage Software Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "taeugi323@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
#resume_contact_telephone:       "555-7334"
#resume_contact_address:         "742 Evergreen Terrace, Springfield"

  #resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "<ul><li>모든 혁신의 시작은 인프라라고 굳게 믿는 개발자입니다.</li><li>철저한 테스트 코드가 인프라를 위협하는 1%의 위험을 걷어낼 수 있다고 생각합니다.</li><li>오픈소스 철학을 좋아하여 다양한 방법으로 오프소스 프로젝트들에 참여합니다.</li><li>어떤 상대와도 소통할 수 있다고 믿으며, 더 힘들수록 더 웃으면서 일합니다.</li></ul>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
#  resume_section_interests:     false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/shellwedance"
    #resume_twitter_url:           "http://twitter.com/jglovier"
    #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/taeuk-kim-3355a5155/"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://joelglovier.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
